In [1]:
import yfinance as yf

In [9]:
data = yf.download(
    "MRNA GOLD ETH-USD XOM DLR BTC-USD NKE OSTK",
    start="2019-01-01", 
    end="2023-06-30"
)

[*********************100%***********************]  8 of 8 completed

In [10]:
data.head

<bound method NDFrame.head of                Adj Close                                                  \
                 BTC-USD         DLR      ETH-USD       GOLD        MRNA
Date
2019-01-01   3843.520020         NaN   140.819412        NaN         NaN
2019-01-02   3943.409424   87.750114   155.047684  11.761898   15.330000
2019-01-03   3836.741211   87.307892   149.135010  11.672113   15.500000
2019-01-04   3857.717529   89.127693   154.581940  11.752922   16.959999
2019-01-05   3845.194580         NaN   155.638596        NaN         NaN
...                  ...         ...          ...        ...         ...
2023-06-25  30480.261719         NaN  1900.506104        NaN         NaN
2023-06-26  30271.130859  107.199997  1859.432861  16.570000  120.410004
2023-06-27  30688.164062  109.019997  1889.703369  16.660000  120.669998
2023-06-28  30086.246094  109.589996  1827.971191  16.600000  123.000000
2023-06-29  30445.351562  111.879997  1852.227295  16.629999  122.110001

                                                      Close              ...  \
                   NKE       OSTK         XOM       BTC-USD         DLR  ...
Date                                                                     ...
2019-01-01         NaN        NaN         NaN   3843.520020         NaN  ...
2019-01-02   70.848526  14.130000   54.902359   3943.409424  103.190002  ...
2019-01-03   69.595322  13.250000   54.059406   3836.741211  102.669998  ...
2019-01-04   71.412964  14.260000   56.052567   3857.717529  104.809998  ...
2019-01-05         NaN        NaN         NaN   3845.194580         NaN  ...
...                ...        ...         ...           ...         ...  ...
2023-06-25         NaN        NaN         NaN  30480.261719         NaN  ...
2023-06-26  111.739998  23.059999  104.290001  30271.130859  107.199997  ...
2023-06-27  113.610001  24.070000  104.550003  30688.164062  109.019997  ...
2023-06-28  113.029999  25.540001  105.400002  30086.246094  109.589996  ...
2023-06-29  113.370003  30.570000  106.699997  30445.351562  111.879997  ...

                 Open                   Volume                         \
                 OSTK         XOM      BTC-USD        DLR     ETH-USD
Date
2019-01-01        NaN         NaN   4324200990        NaN  2258709868
2019-01-02  13.310000   67.349998   5244856836  1411800.0  3328240369
2019-01-03  13.980000   70.000000   4530215219  1511600.0  2676164880
2019-01-04  13.360000   69.639999   4847965467  1474300.0  3126192535
2019-01-05        NaN         NaN   5137609824        NaN  3338211928
...               ...         ...          ...        ...         ...
2023-06-25        NaN         NaN  12703464114        NaN  6937581709
2023-06-26  24.139999  102.199997  16493186997  2477100.0  8619702292
2023-06-27  23.209999  104.050003  16428827944  3855000.0  7686042202
2023-06-28  24.990000  104.309998  14571500779  3539900.0  7135265016
2023-06-29  27.709999  105.660004  13180860821  2783000.0  5677228612


                  GOLD       MRNA         NKE        OSTK         XOM
Date
2019-01-01         NaN        NaN         NaN         NaN         NaN
2019-01-02  16483400.0  2318100.0   6762700.0   1238500.0  16727200.0
2019-01-03  19135900.0  1588900.0   8007400.0   1396300.0  13866100.0
2019-01-04  17190100.0  1651800.0   7844200.0   1708300.0  16043600.0
2019-01-05         NaN        NaN         NaN         NaN         NaN
...                ...        ...         ...         ...         ...
2023-06-25         NaN        NaN         NaN         NaN         NaN
2023-06-26  16119300.0  3466100.0   6887100.0   2394900.0  14283400.0
2023-06-27  15073900.0  2375300.0   7138600.0   2511000.0  13227500.0
2023-06-28  16191800.0  2534300.0   6766000.0   3833500.0  13084100.0
2023-06-29  14737200.0  1886100.0  12465500.0  15445200.0  11364400.0

[1641 rows x 48 columns]>

In [12]:
yf.download(tickers = "MRNA GOLD ETH-USD XOM DLR BTC-USD NKE OSTK",  # list of tickers
            period = "4y",         # time period
            interval = "1d",       # trading interval
            prepost = False,       # download pre/post market hours data?
            repair = True)         # repair obvious price errors e.g. 100x?

[*********************100%***********************]  8 of 8 completed

               Adj Close                                                  \
                 BTC-USD         DLR      ETH-USD       GOLD        MRNA
Date
2019-07-10  12156.512695         NaN   290.002319        NaN         NaN
2019-07-11  11358.662109  104.836601   268.704041  14.766109   14.440000
2019-07-12  11815.986328  104.005035   276.276703  14.874221   14.200000
2019-07-13  11392.378906         NaN   269.458801        NaN         NaN
2019-07-14  10256.058594         NaN   227.578064        NaN         NaN
...                  ...         ...          ...        ...         ...
2023-07-06  29909.337891  114.489998  1848.636475  16.219999  118.290001
2023-07-07  30342.265625  113.800003  1870.602539  16.340000  118.870003
2023-07-08  30292.541016         NaN  1865.539551        NaN         NaN
2023-07-09  30171.234375         NaN  1863.009766        NaN         NaN
2023-07-10  30375.546875  114.010002  1879.686279  16.530001  123.089996

                                                      Close              ...  \
                   NKE       OSTK         XOM       BTC-USD         DLR  ...
Date                                                                     ...
2019-07-10         NaN        NaN         NaN  12156.512695         NaN  ...
2019-07-11   84.914474  17.820000   62.497002  11358.662109  121.029999  ...
2019-07-12   85.712746  19.010000   62.545338  11815.986328  120.070000  ...
2019-07-13         NaN        NaN         NaN  11392.378906         NaN  ...
2019-07-14         NaN        NaN         NaN  10256.058594         NaN  ...
...                ...        ...         ...           ...         ...  ...
2023-07-06  105.099998  27.790001  102.919998  29909.337891  114.489998  ...
2023-07-07  104.459999  29.370001  103.160004  30342.265625  113.800003  ...
2023-07-08         NaN        NaN         NaN  30292.541016         NaN  ...
2023-07-09         NaN        NaN         NaN  30171.234375         NaN  ...
2023-07-10  105.779999  29.580000  104.690002  30375.546875  114.010002  ...

           Repaired?              Volume                                      \
                OSTK    XOM      BTC-USD        DLR      ETH-USD        GOLD
Date
2019-07-10       NaN    NaN  33627574244        NaN  11679985167         NaN
2019-07-11     False  False  28595327690   881200.0  10216287022  15834300.0
2019-07-12     False  False  23534692797   690900.0   8148936015  11436800.0
2019-07-13       NaN    NaN  21042616384        NaN   6716829429         NaN
2019-07-14       NaN    NaN  22486000001        NaN   8578339386         NaN
...              ...    ...          ...        ...          ...         ...
2023-07-06     False  False  21129219509  2248100.0   8905008384  17042100.0
2023-07-07     False  False  13384770155  2007700.0   6468885150   9647800.0
2023-07-08       NaN    NaN   7509378699        NaN   4299007854         NaN
2023-07-09       NaN    NaN   7903327692        NaN   4392863807         NaN
2023-07-10     False  False  14709115904  1974738.0   6310532096  15233919.0


                 MRNA        NKE        OSTK         XOM
Date
2019-07-10        NaN        NaN         NaN         NaN
2019-07-11  1135100.0  3942400.0   4985400.0   6404000.0
2019-07-12  1084300.0  4240900.0  10253200.0   6139000.0
2019-07-13        NaN        NaN         NaN         NaN
2019-07-14        NaN        NaN         NaN         NaN
...               ...        ...         ...         ...
2023-07-06  4849400.0  9923500.0   4874900.0  17961400.0
2023-07-07  2433400.0  7460200.0   3150100.0  21926600.0
2023-07-08        NaN        NaN         NaN         NaN
2023-07-09        NaN        NaN         NaN         NaN
2023-07-10  3398405.0  5343215.0   1947387.0  14863313.0

[1462 rows x 56 columns]

In [13]:
data = yf.download(tickers = "MRNA GOLD ETH-USD XOM DLR BTC-USD NKE OSTK",  # list of tickers
            period = "4y",         # time period
            interval = "1d",       # trading interval
            prepost = False,       # download pre/post market hours data?
            repair = True)         # repair obvious price errors e.g. 100x?

[*********************100%***********************]  8 of 8 completed

In [14]:
data

               Adj Close                                                  \
                 BTC-USD         DLR      ETH-USD       GOLD        MRNA
Date
2019-07-10  12156.512695         NaN   290.002319        NaN         NaN
2019-07-11  11358.662109  104.836609   268.704041  14.766108   14.440000
2019-07-12  11815.986328  104.005035   276.276703  14.874222   14.200000
2019-07-13  11392.378906         NaN   269.458801        NaN         NaN
2019-07-14  10256.058594         NaN   227.578064        NaN         NaN
...                  ...         ...          ...        ...         ...
2023-07-06  29909.337891  114.489998  1848.636475  16.219999  118.290001
2023-07-07  30342.265625  113.800003  1870.602539  16.340000  118.870003
2023-07-08  30292.541016         NaN  1865.539551        NaN         NaN
2023-07-09  30171.234375         NaN  1863.009766        NaN         NaN
2023-07-10  30375.546875  114.010002  1879.686279  16.530001  123.089996

                                                      Close              ...  \
                   NKE       OSTK         XOM       BTC-USD         DLR  ...
Date                                                                     ...
2019-07-10         NaN        NaN         NaN  12156.512695         NaN  ...
2019-07-11   84.914452  17.820000   62.496979  11358.662109  121.029999  ...
2019-07-12   85.712753  19.010000   62.545326  11815.986328  120.070000  ...
2019-07-13         NaN        NaN         NaN  11392.378906         NaN  ...
2019-07-14         NaN        NaN         NaN  10256.058594         NaN  ...
...                ...        ...         ...           ...         ...  ...
2023-07-06  105.099998  27.790001  102.919998  29909.337891  114.489998  ...
2023-07-07  104.459999  29.370001  103.160004  30342.265625  113.800003  ...
2023-07-08         NaN        NaN         NaN  30292.541016         NaN  ...
2023-07-09         NaN        NaN         NaN  30171.234375         NaN  ...
2023-07-10  105.779999  29.580000  104.690002  30375.546875  114.010002  ...

           Repaired?              Volume                                      \
                OSTK    XOM      BTC-USD        DLR      ETH-USD        GOLD
Date
2019-07-10       NaN    NaN  33627574244        NaN  11679985167         NaN
2019-07-11     False  False  28595327690   881200.0  10216287022  15834300.0
2019-07-12     False  False  23534692797   690900.0   8148936015  11436800.0
2019-07-13       NaN    NaN  21042616384        NaN   6716829429         NaN
2019-07-14       NaN    NaN  22486000001        NaN   8578339386         NaN
...              ...    ...          ...        ...          ...         ...
2023-07-06     False  False  21129219509  2248100.0   8905008384  17042100.0
2023-07-07     False  False  13384770155  2007700.0   6468885150   9647800.0
2023-07-08       NaN    NaN   7509378699        NaN   4299007854         NaN
2023-07-09       NaN    NaN   7903327692        NaN   4392863807         NaN
2023-07-10     False  False  14709115904  1974738.0   6310532096  15233919.0


                 MRNA        NKE        OSTK         XOM
Date
2019-07-10        NaN        NaN         NaN         NaN
2019-07-11  1135100.0  3942400.0   4985400.0   6404000.0
2019-07-12  1084300.0  4240900.0  10253200.0   6139000.0
2019-07-13        NaN        NaN         NaN         NaN
2019-07-14        NaN        NaN         NaN         NaN
...               ...        ...         ...         ...
2023-07-06  4849400.0  9923500.0   4874900.0  17961400.0
2023-07-07  2433400.0  7460200.0   3150100.0  21926600.0
2023-07-08        NaN        NaN         NaN         NaN
2023-07-09        NaN        NaN         NaN         NaN
2023-07-10  3398405.0  5289553.0   1947387.0  14863313.0

[1462 rows x 56 columns]

In [18]:
data = data.drop(columns=['Adj Close', 'High', 'Low'])

In [20]:
data.columns

MultiIndex([(    'Close', 'BTC-USD'),
            (    'Close',     'DLR'),
            (    'Close', 'ETH-USD'),
            (    'Close',    'GOLD'),
            (    'Close',    'MRNA'),
            (    'Close',     'NKE'),
            (    'Close',    'OSTK'),
            (    'Close',     'XOM'),
            (     'High', 'BTC-USD'),
            (     'High',     'DLR'),
            (     'High', 'ETH-USD'),
            (     'High',    'GOLD'),
            (     'High',    'MRNA'),
            (     'High',     'NKE'),
            (     'High',    'OSTK'),
            (     'High',     'XOM'),
            (      'Low', 'BTC-USD'),
            (      'Low',     'DLR'),
            (      'Low', 'ETH-USD'),
            (      'Low',    'GOLD'),
            (      'Low',    'MRNA'),
            (      'Low',     'NKE'),
            (      'Low',    'OSTK'),
            (      'Low',     'XOM'),
            (     'Open', 'BTC-USD'),
            (     'Open',     'DLR'),
            (     'Open', 'ETH-USD'),
            (     'Open',    'GOLD'),
            (     'Open',    'MRNA'),
            (     'Open',     'NKE'),
            (     'Open',    'OSTK'),
            (     'Open',     'XOM'),
            ('Repaired?', 'BTC-USD'),
            ('Repaired?',     'DLR'),
            ('Repaired?', 'ETH-USD'),
            ('Repaired?',    'GOLD'),
            ('Repaired?',    'MRNA'),
            ('Repaired?',     'NKE'),
            ('Repaired?',    'OSTK'),
            ('Repaired?',     'XOM'),
            (   'Volume', 'BTC-USD'),
            (   'Volume',     'DLR'),
            (   'Volume', 'ETH-USD'),
            (   'Volume',    'GOLD'),
            (   'Volume',    'MRNA'),
            (   'Volume',     'NKE'),
            (   'Volume',    'OSTK'),
            (   'Volume',     'XOM')],
           )